Update README.md
opencontainers/artifacts pull request #68
Opened 2023-07-13 18:28 UTC by mikebrow

make a bold notice regarding where people should go for guidance

2023-07-13 21:30 UTC, jdolitsky requested changes
IMO the README is still misleading because it is so long. Can we create a file called README_ARCHIVED.md to maintain all this stuff, then do something like i suggest here? https://github.com/opencontainers/tob/issues/126#issuecomment-1634942682

2023-07-13 21:56 UTC, mikebrow commented
> IMO the README is still misleading because it is so long. Can we create a file called README_ARCHIVED.md to maintain all this stuff, then do something like i suggest here? [opencontainers/tob#126 (comment)](https://github.com/opencontainers/tob/issues/126#issuecomment-1634942682)

Appreciate the perspective.. Let's treat this (modifying this repo's readme with a quick succession of prs) as a work in progress moving in that ^ direction, cutting out the parts that don't need to be here (should not be here) as those parts show up in the 1.1 specs and probably including a few more tabs (here) than you have suggested just to preserve external links for redirection to the new suggested spec doc sub tabs in said artifact author guidance as it gets merged in. No reason to merge pointing to links that are not there yet :-)

2023-07-14 18:26 UTC, jdolitsky approved these changes
LGTM

2023-07-14 19:20 UTC, vbatts approved these changes

2023-07-15 02:24 UTC, dmcgowan approved these changes

2023-07-17 04:47 UTC, SteveLasker requested changes
See PR #70 for some additional wording. 
**Note:** this also depends on https://github.com/opencontainers/image-spec/pull/1095 for the artifacts-guidance.md link

2023-07-17 04:47 UTC, SteveLasker commented on README.md
> +## Mission Update
the act of archiving, and directing users to the new reopos is a bit redundant to. See proposed changes in #70

2023-07-17 13:54 UTC, mikebrow commented
merged into #70 for additional context

2023-07-17 13:58 UTC, merged